### ISSUE TITLE
[BUG] Wrong background color of hovered list group items in dark mode

### ISSUE THREAD

**Issue by df2** [tabler/tabler#1035]
**Describe the bug**

Non-active list group items have a light background in dark mode when hovered over.

**To reproduce**

Create a list group of ```<a>```'s and hover over one in dark mode.

**Screenshots**

![Screenshot_20220211_095234](https://user-images.githubusercontent.com/1834925/153644029-aa3782f9-652b-4596-85f4-37e7c983be81.png)
![Screenshot_20220211_095254](https://user-images.githubusercontent.com/1834925/153644023-da0eda41-0db5-498c-abc6-f83ee9e9f754.png)

List groups in the second column with second item hovered in regular and dark mode.

**Comment by codecalm** [comment]
fixed :)

**Comment by df2** [comment]
Looks like there's still an issue with the `:active` state in dark mode:

![Screenshot_20220221_052709](https://user-images.githubusercontent.com/1834925/154964244-6e21dcff-9998-4f28-9620-4531b588f469.png)
