### ISSUE TITLE
[BUG] Term of service page is truncated

### ISSUE THREAD

**Issue by gustavi** [tabler/tabler#1453]
**Describe the bug**

The top of the page https://preview.tabler.io/terms-of-service.html on beta17 (I'm note sure is was working as expected in beta16) is truncated.

**Device**

 - Browser: Firefox 102.7.0esr (64-bit)
 - OS: GNU/Linux
 - Screen size: 1920x1080

**To reproduce**

1. Go to https://preview.tabler.io/terms-of-service.html
2. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/2736557/216268047-f6515247-bea8-4233-8195-5592ac1be5f1.png)

**Comment by tinyoverflow** [comment]
This is because the first div inside the body has the two classes `.page` and `.page-center`. The `.page`-class sets `flex-direction: column`. Therefore, the `justify-content: center` property set by the `.page-center` class now controls the vertical alignment instead.

https://github.com/tabler/tabler/blob/14af3c7c1c850bfa7d343f93ee7eb0f50718dfd3/src/scss/layout/_page.scss#L1-L10


---

In this case, the `.page-center` class is not even required anymore, as the centering is done on the `body` element.

**Comment by codecalm** [comment]
I've fixed it! :) thank you for help ❤️

**Comment by keskinonur** [comment]
This issue is still ongoing in beta 20. 

https://dev.tabler.io/terms-of-service.html
