### ISSUE TITLE
[BUG] active tab in dark mode is white

### ISSUE THREAD

**Issue by dheineman** [tabler/tabler#897]
**Describe the bug**

I am not sure if this is intentional but in case it is not here goes.

When using the dark theme for tabler the active tab has a bright white color

**Device**

 - Browser: Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)
 - OS: MacOS 11.2.3
 - Screen size: 2560×1440

**To reproduce**

1. Go to https://preview.tabler.io/tabs.html
2. Open the element inspector and add the `theme-dark` class to the body

**Screenshots**

![Screenshot 2021-07-16 at 11 19 36](https://user-images.githubusercontent.com/516028/125924749-134b1114-87e2-46b6-b3c1-f3bb6a252d83.png)

**Comment by kevinpapst** [comment]
@codecalm could you share some insights on this topic? Is it by intention that the tabs are the only (as far as I could see) elements with pure white borders and such a strong accent color or are you open for changes here?

**Comment by codecalm** [comment]
I'll check it

**Comment by rjd22** [comment]
This is fixed now

**Comment by kevinpapst** [comment]
@rjd22 this is not fixed, see https://preview.tabler.io/tabs.html

<img width="491" alt="Bildschirmfoto 2022-03-24 um 10 53 56" src="https://user-images.githubusercontent.com/533162/159890275-82841b92-3ee1-471a-9fd5-d189cb9a10d3.png">

Or is this really intentional?
